server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://mengali:messi10@wakanda.ceoegte.mongodb.net/wakanda?appName=wakanda}
      auto-index-creation: true


springdoc:
  swagger-ui:
    path: /swagger