server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      uri: mongodb+srv://cauanmengali10_db_user:grovyle10@wakanda.4dxrfol.mongodb.net/?appName=wakanda
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger