server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://cauan:grovyle10@cluster0.zmqxdb2.mongodb.net/Cluster0?appName=Cluster0}
      auto-index-creation: true


springdoc:
  swagger-ui:
    path: /swagger